---
title: "R&D Emerging Digitalization Trends"
output:
  html_document:
    includes:
      in_header: hero-image.html
---

#**Project Background**  
Around 21% of all research and development (R&D) funding in the United States is provided by the federal government. The [Federal RePORTER](https://wayback.archive-it.org/18816/20220223125200/https:/federalreporter.nih.gov/FileDownload) database contains 1.2 million grant abstracts and metadata from HHS, NSF, USDA, NASA, DOD, VA, ED, and EPA between 2008 and 2020.

# **Research Question**
How can we characterize the R&D digitalization research area that the funding supported? What are trends in the digitalization research area?

# **Prior Work**
Topic modeling, term matching, and latent semantic indexing on the [case study topic of pandemics.](https://github.com/uva-bi-sdad/publicrd/tree/master/src/Paper/05_case_studies)  

#**Sponsor**  
This project is sponsored by the National Center for Science and Engineering Statistics (NCSES), a principal staistical agency located within the National Science Foundation. The project stakeholders from NCSES are John Jankowski, Senior Economic Advisor, and Audrey Kindlon, Survey Statistician.


# **Method**  
##Literature Review   
We conducted a literature review to define digitalizaiton and sub-themes of big data. These definitions were used to create our training set for our supervised learning methods. We also explored different learning models that could be used to determine which abstracts pertain to certain themes.  


##Word Vectorization  
We used TF-IDF and Doc2Vec models to transform our corpus of abstracts into vector representations of each document.   


##Text Classifiers  
The vectorized words were inputed into a KNN text classifier to determine which abstracts relate to digitalization and more specifically the sub theme of big data.

  
 






<!-- Here's how you make a list: -->

<!-- *Tips for making figures look good:* -->

<!-- - Make text sizes BIG -->
<!-- - Stick to the same colors -->
<!-- - Decide to add titles, captions, etc in the figures OR add on the website for all figures -->

